server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_music?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: music
    password: music
  jpa:
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    # 文件上传配置
    multipart:
      enabled: true
      max-file-size: 64MB
      max-request-size: 256MB
  # 静态资源配置
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations:
        - classpath:/static
        - classpath:/public
        - classpath:/resources
        - classpath:/META-INF/resources
        - file:upload
  jackson:
    # json时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 邮件配置
  mail:
    default-encoding: UTF-8
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    properties:
      mail.smtp.ssl.enable: true

